/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author TheUltimateGamer
 */
public class AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPanel
     */
    public AddPanel() {
        initComponents();
        initComponents2();
    }
    
   void initComponents2(){
        jPanel1.hide();
        setPreferredSize(new Dimension(0, 105));
        this.setBorder(new LineBorder(Color.black));
        Icon.setIcon(new javax.swing.ImageIcon("icons\\plus.png")); 
        ResIcon.setIcon(new javax.swing.ImageIcon("icons\\plus.png"));
        Cancel.setIcon(new javax.swing.ImageIcon("icons\\delete.png"));



}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ResIcon = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Desc = new javax.swing.JTextField();
        MinLabel = new javax.swing.JLabel();
        Cancel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(510, 105));
        setMinimumSize(new java.awt.Dimension(510, 105));
        setLayout(null);

        jPanel1.setLayout(null);

        ResIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResIconMouseClicked(evt);
            }
        });
        jPanel1.add(ResIcon);
        ResIcon.setBounds(5, 5, 90, 90);

        Time.setToolTipText("Restaurant Time");
        jPanel1.add(Time);
        Time.setBounds(110, 70, 90, 22);

        Name.setToolTipText("Restaurant Name");
        jPanel1.add(Name);
        Name.setBounds(110, 10, 240, 22);

        Desc.setToolTipText("Restaurant Description");
        jPanel1.add(Desc);
        Desc.setBounds(110, 40, 190, 22);

        MinLabel.setText("Min");
        jPanel1.add(MinLabel);
        MinLabel.setBounds(210, 73, 30, 16);

        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        jPanel1.add(Cancel);
        Cancel.setBounds(447, 10, 30, 30);

        add(jPanel1);
        jPanel1.setBounds(5, 2, 500, 100);

        jPanel2.setLayout(null);

        Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMouseClicked(evt);
            }
        });
        jPanel2.add(Icon);
        Icon.setBounds(200, 10, 90, 90);

        add(jPanel2);
        jPanel2.setBounds(5, 2, 500, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMouseClicked
        jPanel2.hide();
        jPanel1.show();

        
        
    }//GEN-LAST:event_IconMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        jPanel1.hide();
        jPanel2.show();
        Desc.setText("");
        Name.setText("");
        Time.setText("");
        ResIcon.setIcon(new javax.swing.ImageIcon("icons\\plus.png"));

        
        
// TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseClicked

    private void ResIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResIconMouseClicked
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());


        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select an image");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "png");

        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        
        // Check if a file was selected
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            ResIcon.setIcon(new javax.swing.ImageIcon(filePath));

        }
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
                }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_ResIconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cancel;
    private javax.swing.JTextField Desc;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel ResIcon;
    private javax.swing.JTextField Time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
