/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import org.jxmapviewer.viewer.GeoPosition;
import waypoint.MyWaypoint;

/**
 *
 * @author TheUltimateGamer
 */
public class CheckOutPanel extends javax.swing.JPanel implements FrameClosedCallback {

    /**
     * Creates new form CheckOutPanelTest
     */
    private javax.swing.JFrame frame;
    private Cart c;
    private int state;
    public CheckOutPanel(javax.swing.JFrame frame , Cart c , int state) {
        this.c = c;
        this.frame = frame;
        this.state = state;
        initComponents();
        initComponents2();
        
    }
    
    private void initComponents2(){
        setPreferredSize(new Dimension(0, 105));
        this.setBorder(new LineBorder(Color.black));
        Address.setText(c.getAddress());
        if(state == 2){
            Action_Button.hide();
        
        }else{
        //******** CHeckout button that confarmed order and send cart objects to order history ***********//
        
        Action_Button.setBackground(new java.awt.Color(102, 102, 102));
        Action_Button.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12));
        Action_Button.setForeground(new java.awt.Color(255, 255, 255));
        Action_Button.setText("Checkout");
        
        Action_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodDelivery.user.getOrders().AddAndSavetoOrders(FoodDelivery.user.getCart());
                JOptionPane.showMessageDialog(frame, "Order Confirmed",
                "Success", JOptionPane.INFORMATION_MESSAGE);
                FoodDelivery.user.getCart().ClearCart();
                CartForm cf = new CartForm(FoodDelivery.user.getCart(),state);
                cf.setVisible(true);
                cf.setLocation(frame.getLocationOnScreen());
                frame.setVisible(false);
                

                
                
            }
        });
        }
        //******** calculate invoice  of order  ***********//
        Sub_Total.setText( c.getSubTotal() +" EGP");

        Delivery_Fees_Label.setText("Delivery Fees: ");

        Total_Label.setFont(new java.awt.Font("Segoe UI", 1, 18));
        Total_Label.setText("Total: ");

        Delivery_Fees.setText( c.getDeliveryFees()+" EGP");

        Total.setFont(new java.awt.Font("Segoe UI", 1, 14));
        
        Total.setText(c.getTotal()+" EGP");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10));
        jLabel7.setText("Inclusive of VAT 14% i.e. "+ c.getVAT() +" EGP");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Action_Button = new javax.swing.JButton();
        Sub_Total_Label = new javax.swing.JLabel();
        Sub_Total = new javax.swing.JLabel();
        Delivery_Fees_Label = new javax.swing.JLabel();
        Delivery_Fees = new javax.swing.JLabel();
        Total_Label = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 105));
        setMinimumSize(new java.awt.Dimension(500, 105));
        setPreferredSize(new java.awt.Dimension(500, 105));
        setRequestFocusEnabled(false);

        Action_Button.setText("Checkout");

        Sub_Total_Label.setText("Sub Total:");

        Sub_Total.setText("160.0 EGP");

        Delivery_Fees_Label.setText("Delivery Fees:");

        Delivery_Fees.setText("20 EGP");

        Total_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Total_Label.setText("Total:");

        Total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Total.setText("180.0 EGP");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("Inclusive of VAT 14% i.e. 22.40 EGP");

        Address.setText("Address");
        Address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sub_Total_Label)
                    .addComponent(Delivery_Fees_Label)
                    .addComponent(Total_Label)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Delivery_Fees)
                                    .addComponent(Total))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(Action_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sub_Total)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sub_Total_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delivery_Fees_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total_Label))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Action_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Sub_Total)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Delivery_Fees)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Total))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Address))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressMouseClicked

            MapForm mf = new MapForm(this,state);
            mf.addWaypoint(new MyWaypoint(new GeoPosition(c.getLat(), c.getLon())));
            mf.addroute(24.089015072633437, 32.89867204002298, c.getLat(), c.getLon());
            mf.setVisible(true);
            
        
    }//GEN-LAST:event_AddressMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action_Button;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Delivery_Fees;
    private javax.swing.JLabel Delivery_Fees_Label;
    private javax.swing.JLabel Sub_Total;
    private javax.swing.JLabel Sub_Total_Label;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Total_Label;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onFrameClosed(String data) {
        
    }

    @Override
    public void onFrameClosed(String Address, double lat, double lon) {
        FoodDelivery.user.getCart().setAddress(Address);
        FoodDelivery.user.getCart().setLat(lat);
        FoodDelivery.user.getCart().setLon(lon);
        this.Address.setText(Address);
        this.Delivery_Fees.setText(c.getDeliveryFees());
        this.Total.setText(c.getTotal());
    }
}
