/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.border.LineBorder;

/**
 *
 * @author TheUltimateGamer
 */
public class DishesPanel extends javax.swing.JPanel {

    /**
     * Creates new form DishesPanelTest
     */
    private javax.swing.JFrame frame;
    private Dish dish;
    private int state;
    
    private String ResName;
    public DishesPanel(javax.swing.JFrame frame,Dish dish , int state) {
        this.dish = dish;
        this.frame = frame;
        this.state = state;
        initComponents();
        initComponents2();
    }
    
    
    private void initComponents2(){
        setPreferredSize(new Dimension(0, 105));

        Icon.setIcon(new javax.swing.ImageIcon("icons\\" + dish.getName() + ".png")); 

        Dish_Name.setFont(new java.awt.Font("Segoe UI", 0, 24));
        Dish_Name.setText(dish.getName());

        Dish_Description.setText(dish.getDesc());

        Dish_Price.setText(dish.getPrice() + " EGP");

        if(state == 2){
            Action_Button.hide();
        }
        
        
        if(state ==0){
        Action_Button.setText("Add to Cart");
        }else if(state == 1){
        Action_Button.setText("Remove");
        }
        
        Action_Button.addActionListener(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { 
            
            if(state ==0){
               FoodDelivery.user.getCart().AddAndSavetoCart(dish);
            }else if(state==1){
            FoodDelivery.user.getCart().RemoveFromCartAndSave(dish);
            
            CartForm cf = new CartForm(FoodDelivery.user.getCart(),1);
            cf.setVisible(true);
            cf.setLocation(frame.getLocationOnScreen());
            frame.setVisible(false);
            
            
            }
        } 
      } );
    
            this.setBorder(new LineBorder(Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Action_Button = new javax.swing.JButton();
        Dish_Name = new javax.swing.JLabel();
        Dish_Description = new javax.swing.JLabel();
        Dish_Price = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(510, 105));

        Action_Button.setText("Add to Cart");

        Dish_Name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dish_Name.setText("Cheering Box");

        Dish_Description.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Dish_Description.setText("3 twister sandwiches, 6 pieces of chicken, family french fries and pepsi liter.");

        Dish_Price.setText("282.99 EGP");
        Dish_Price.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dish_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dish_Price)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dish_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Action_Button)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dish_Name)
                            .addComponent(Action_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Dish_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dish_Price))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action_Button;
    private javax.swing.JLabel Dish_Description;
    private javax.swing.JLabel Dish_Name;
    private javax.swing.JLabel Dish_Price;
    private javax.swing.JLabel Icon;
    // End of variables declaration//GEN-END:variables
}
