/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.border.LineBorder;

/**
 *
 * @author TheUltimateGamer
 */
public class MessagesPanel extends javax.swing.JPanel {

    /**
     * Creates new form DishesPanelTest
     */
    private javax.swing.JFrame frame;
    Cart c;
    Message m;
    public MessagesPanel(javax.swing.JFrame frame ,Cart c,Message m) {
        
        this.frame = frame;
        this.c = c;
        this.m = m;
        initComponents();
        initComponents2();
    }
    
    
    private void initComponents2(){
        setPreferredSize(new Dimension(0, 105));
    
        if(m.getFrom().equals(FoodDelivery.user.getName())){
            Icon.setIcon(new javax.swing.ImageIcon("icons\\MessageSent.png"));      
        }else{
            Icon.setIcon(new javax.swing.ImageIcon("icons\\MessageRecieved.png"));
        }
       
        Title.setFont(new java.awt.Font("Segoe UI", 0, 24));
        User.setFont(new java.awt.Font("Segoe UI", 0, 24));
        User.setText(m.getFrom());
        Title.setText(m.getTitle());

        
        
        
        this.setBorder(new LineBorder(Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        User = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(510, 105));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Testing");

        User.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        User.setText("Testing");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(User)
                        .addGap(32, 324, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(User)
                        .addGap(12, 12, 12)
                        .addComponent(Title)
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
            MessagesFrameView mf = new MessagesFrameView(m);
            mf.setVisible(true);
            mf.setVisible(true);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                
            // Calculate the center position
            int centerX = (screenSize.width - mf.getWidth()) / 2;
            int centerY = (screenSize.height - mf.getHeight()) / 2;

            // Set the frame's location to the center
            mf.setLocation(centerX, centerY);
        
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel User;
    // End of variables declaration//GEN-END:variables
}
