/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author TheUltimateGamer
 */
public class NewMessagePanel extends javax.swing.JPanel  implements FrameClosedCallback{

    Cart c;
    FrameClosedCallback fb;
     private javax.swing.JFrame frame;
    /**
     * Creates new form AddPanel
     */
    public NewMessagePanel(javax.swing.JFrame frame,Cart c) {
        this.c = c;
        this.fb = fb;
        this.frame = frame;
        initComponents();
        initComponents2();
    }
    
   void initComponents2(){
        setPreferredSize(new Dimension(0, 105));
        this.setBorder(new LineBorder(Color.black));
        Icon.setIcon(new javax.swing.ImageIcon("icons\\plus.png")); 

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(510, 105));
        setMinimumSize(new java.awt.Dimension(510, 105));
        setLayout(null);

        jPanel2.setLayout(null);

        Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMouseClicked(evt);
            }
        });
        jPanel2.add(Icon);
        Icon.setBounds(200, 10, 90, 90);

        add(jPanel2);
        jPanel2.setBounds(5, 2, 500, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMouseClicked
        
            MessagesFrame JMessagesFrame = new MessagesFrame(c,this);
            JMessagesFrame.setVisible(true);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                
            // Calculate the center position
            int centerX = (screenSize.width - JMessagesFrame.getWidth()) / 2;
            int centerY = (screenSize.height - JMessagesFrame.getHeight()) / 2;

            // Set the frame's location to the center
            JMessagesFrame.setLocation(centerX, centerY);

        
        
    }//GEN-LAST:event_IconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onFrameClosed(String data) {
      MessagesForm mf = new MessagesForm(c);
        mf.setVisible(true);
        mf.setLocation(frame.getLocationOnScreen());
        frame.setVisible(false);
        
        
    }

}
