/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;

/**
 *
 * @author TheUltimateGamer
 */
public class RestaurantPanel extends javax.swing.JPanel {
    private javax.swing.JFrame frame;
    private Restaurant res;
    /**
     * Creates new form RestaurantPanelTest
     */
    public RestaurantPanel(boolean empty){

    }
    public RestaurantPanel(javax.swing.JFrame frame,Restaurant res) {
        this.frame = frame;
        this.res = res;
        initComponents();
        initComponents2();
    }
    
    
    private void initComponents2(){
        setPreferredSize(new Dimension(0, 105));

        if(FoodDelivery.user.getPermission()!=0){
        del.hide();
        }else{
            del.setIcon(new javax.swing.ImageIcon("icons\\delete.png"));
        }
        
        
        
        Icon.setIcon(new javax.swing.ImageIcon("icons\\" + res.getName() + ".png"));

        Name.setFont(new java.awt.Font("Segoe UI", 0, 24));
        Name.setText(res.getName());

        Description.setText(res.getDesc());

        Time.setText(res.getTime()+" Min");

        
        
//        Rate.setText(res.getRate());
            Rate.setText("");
            int r = (int)Double.parseDouble(res.getRate());
           Rate.setIcon(new javax.swing.ImageIcon("icons\\rate"+r+".png"));

           
        this.setBorder(new LineBorder(Color.black));

        
        addMouseListener(new MouseAdapter() {

                @Override
                public void mousePressed(MouseEvent e) {
                     DishesForm DF = new DishesForm(res.getName(),0);
                     DF.setVisible(true);
                     DF.setLocation(frame.getLocationOnScreen());
                     frame.setVisible(false);

                }
            });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Rate = new javax.swing.JLabel();
        del = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(555, 105));
        setLayout(null);
        add(Icon);
        Icon.setBounds(6, 6, 96, 93);

        Name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Name.setText("KFC");
        add(Name);
        Name.setBounds(114, 6, 310, 32);

        Description.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Description.setText("Sandwitch ,Fried Chicken");
        add(Description);
        Description.setBounds(114, 44, 351, 16);

        Time.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Time.setText("45 Min");
        add(Time);
        Time.setBounds(114, 66, 120, 16);

        Rate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Rate.setText("4.0");
        add(Rate);
        Rate.setBounds(420, 70, 130, 20);

        del.setPreferredSize(new java.awt.Dimension(30, 30));
        del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delMouseClicked(evt);
            }
        });
        add(del);
        del.setBounds(488, 6, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delMouseClicked
        res.DeleteResturant();
        RestaurantForm jframeRestaurantForm = new RestaurantForm();
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        jframeRestaurantForm.setVisible(true);
        jframeRestaurantForm.setLocation(frame.getLocationOnScreen());
        frame.setVisible(false);
        
        
        
    }//GEN-LAST:event_delMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Rate;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel del;
    // End of variables declaration//GEN-END:variables
}
