/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.fooddelivery;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import java.awt.event.*;  
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author EL-YaMaMa
 */
public class RestaurantForm extends javax.swing.JFrame  implements ActionListener{

    /**
     * Creates new form RestaurantForm
     */
              JMenuItem i1, i2, i3, i4, i5;  

    public RestaurantForm() {
        initComponents();
        
         JMenu menu, submenu,username;  
 
          JMenuBar mb=new JMenuBar();  
          menu=new JMenu("☰");  
          submenu=new JMenu("Sub Menu");  
          i1=new JMenuItem("Order History");  
          i2=new JMenuItem("My Favourites");  
          i3=new JMenuItem("Logout");  
          
          i1.addActionListener(this);  
          i3.addActionListener(this);   

          
          menu.add(i1); menu.add(i2); menu.add(i3);  
//          submenu.add(i4); submenu.add(i5);  
//          menu.add(submenu); 
//          menu.add(submenu);  
          username =  new JMenu(FoodDelivery.user.getName());
//                    username =  new JMenu("TEST");


          mb.add(menu);
          mb.add(username);
          
          this.setJMenuBar(mb);   
          this.setVisible(true);  

//---------------------------


        final int FRAME_WIDTH = 555;
        final int FRAME_HEIGHT = 800;

        this.setSize(FRAME_WIDTH, FRAME_HEIGHT);
        this.setTitle("Home Library");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLayout(new FlowLayout());
        
//        this.setTitle("home libaray");

        // Top Panel
//        JPanel p1 = new JPanel();
//        p1.setLayout(new FlowLayout());
//        p1.setBackground(Color.LIGHT_GRAY);
//        p1.setPreferredSize(new Dimension(950, 100));
//
//        JLabel l1 = new JLabel("All Library Items");
//        l1.setForeground(Color.BLACK);
//        l1.setPreferredSize(new Dimension(900, 50));
//        l1.setFont(l1.getFont().deriveFont(30.0f));
//
//        p1.add(l1);

        // Content Panel
        JPanel p2 = new JPanel();


        p2.setLayout(new GridLayout(-1, 1));
        p2.setBackground(Color.LIGHT_GRAY);
        // p2.setPreferredSize(new Dimension(950, 800));
        p2.setAutoscrolls(true);

        JScrollPane scrollPane = new JScrollPane(p2);
        scrollPane.setHorizontalScrollBarPolicy(
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        // scrollPane.setBounds(0, 0, 950, 800);
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);

        JPanel contentPane = new JPanel(new BorderLayout());
        contentPane.setPreferredSize(new Dimension(540, 905));
        contentPane.add(scrollPane, BorderLayout.CENTER);


            Color[] c = {Color.RED,Color.GREEN,Color.BLUE};
        for (int i = 0; i < 10; i++) {

            JPanel sp1 = new RestaurantPanel(this);
            



            p2.add(sp1);

        }

        // contentPane.add(p2);
//        contentPane.add(p1, BorderLayout.NORTH);
        // frame.add(p2);
        // frame.setContentPane(contentPane);
        this.add(contentPane);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {    
        if(e.getSource()==i3) {
            System.out.println("yes");
        Login JframeLogin = new Login();
        JframeLogin.setVisible(true);
        JframeLogin.setLocation(this.getLocationOnScreen());
        this.setVisible(false);
        }
}     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
